# create a Role Binding, which is used to make the connection between the Role and the Service Account

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: system:serviceaccount:db:default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: default
subjects:
- kind: ServiceAccount
  name: default
  namespace: db